#include <iostream>
#define CURL_STATICLIB
#include <dpp/dpp.h>
#include <Windows.h>
#include <fstream>
#include <stdio.h>
#include <string>
#include "progressbar.hpp"
#include <tchar.h>
#include <urlmon.h>
#include <thread>
#include <sstream>
#include <curl/curl.h>
#include <conio.h>
#include <sstream>
#include <json.hpp>
#include <sys/stat.h>
#include <filesystem>
#include <regex>=