#pragma once
#include <iostream>
#include <dpp/dpp.h>
#include <Windows.h>
#include <fstream>
#include <stdio.h>
#include <string>
#include <tchar.h>
#include <urlmon.h>
#include <thread>
#include <sstream>
#include <curl/curl.h>
#include <conio.h>
#include <sstream>
#include <json.hpp>
#include <sys/stat.h>
#include <filesystem>
#include <regex>
#include <direct.h>
#include <locale>
#include <codecvt>
#include <string>
#include <curlpp/cURLpp.hpp>
#include <curlpp/Easy.hpp>
#include <curlpp/Options.hpp>
#include <curlpp/Types.hpp>
#include <curlpp/Exception.hpp>
#include <curlpp/Form.hpp>
#include <curlpp/Infos.hpp>
#include <list>
#include <cpr/cpr.h>
#include "progressbar.hpp"